// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Context;

#nullable disable

namespace Service.Migrations
{
    [DbContext(typeof(OfferCategoryDbContext))]
    [Migration("20260920073339_AddCappingRulesTable")]
    partial class AddCappingRulesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interface.DTOs.CappingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffiliateVisibility")
                        .HasColumnType("text");

                    b.Property<bool?>("CappingTimezoneEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CappingType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CappingValue")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EarlierNotificationThreshold")
                        .HasColumnType("numeric");

                    b.Property<bool?>("EnableRule")
                        .HasColumnType("boolean");

                    b.Property<string>("Events")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("OverCappingAction")
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.Property<string>("RuleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CappingRules");
                });

            modelBuilder.Entity("Interface.DTOs.Creative", b =>
                {
                    b.Property<long>("CreativeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CreativeID"));

                    b.Property<string>("AffiliateTrackingURL")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferID")
                        .HasColumnType("bigint");

                    b.Property<string>("Preview")
                        .HasColumnType("text");

                    b.Property<decimal?>("Size")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("CreativeID");

                    b.ToTable("Creative");
                });

            modelBuilder.Entity("Interface.DTOs.LandingPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AffiliateId")
                        .HasColumnType("bigint");

                    b.Property<string>("AffiliateMode")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Fallback")
                        .HasColumnType("boolean");

                    b.Property<string>("FallbackName")
                        .HasColumnType("text");

                    b.Property<string>("FallbackUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("FallbackWeight")
                        .HasColumnType("numeric");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("Targeting")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .HasColumnType("text");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LandingPage");
                });

            modelBuilder.Entity("Interface.DTOs.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvertiserCurrency")
                        .HasColumnType("text");

                    b.Property<int?>("AdvertiserId")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertiserModel")
                        .HasColumnType("text");

                    b.Property<decimal?>("AdvertiserPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("AdvertiserUrlBuilder")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateCurrency")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateModel")
                        .HasColumnType("text");

                    b.Property<decimal?>("AffiliatePrice")
                        .HasColumnType("numeric");

                    b.Property<bool?>("AlertToAffiliates")
                        .HasColumnType("boolean");

                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("DailyEndTime")
                        .HasColumnType("interval");

                    b.Property<bool?>("DailyScheduleEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("DailyStartTime")
                        .HasColumnType("interval");

                    b.Property<bool?>("DeepLinks")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalOfferId")
                        .HasColumnType("text");

                    b.Property<bool?>("HidePayout")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LandingPage")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OfferCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("OfferDescription")
                        .HasColumnType("text");

                    b.Property<string>("OfferName")
                        .HasColumnType("text");

                    b.Property<string>("OfferPreviewUrl")
                        .HasColumnType("text");

                    b.Property<string>("OfferType")
                        .HasColumnType("text");

                    b.Property<string>("OfferUrl")
                        .HasColumnType("text");

                    b.Property<string>("OfferVisibility")
                        .HasColumnType("text");

                    b.Property<string>("PaOfferTerms")
                        .HasColumnType("text");

                    b.Property<string>("PrivateNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Styles")
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<string>("Tokens")
                        .HasColumnType("text");

                    b.Property<string>("UploadLogo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("Interface.DTOs.OfferCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferCategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("OfferCategory", (string)null);
                });

            modelBuilder.Entity("Interface.DTOs.TargetingRules", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionOnClicks")
                        .HasColumnType("text");

                    b.Property<string>("ActionOnConversions")
                        .HasColumnType("text");

                    b.Property<string>("ActionOnImpressions")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateVisibility")
                        .HasColumnType("text");

                    b.Property<string>("Browser")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ISP")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TargetingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
