// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.Context;

#nullable disable

namespace Service.Migrations
{
    [DbContext(typeof(OfferCategoryDbContext))]
    [Migration("20260929085824_AddNetworkSettingTrackingColumns")]
    partial class AddNetworkSettingTrackingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Interface.DTOs.AntiFraudSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BrowserBlankReferral")
                        .HasColumnType("text");

                    b.Property<string>("ClickBlockFiltersJson")
                        .HasColumnType("text");

                    b.Property<string>("ClickIpv4RangeFilter")
                        .HasColumnType("text");

                    b.Property<string>("ClickIpv4RangeValues")
                        .HasColumnType("text");

                    b.Property<string>("ClickSpammingDefender")
                        .HasColumnType("text");

                    b.Property<string>("ConversionValidateFiltersJson")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CtitRulesJson")
                        .HasColumnType("text");

                    b.Property<string>("DefaultIpSource")
                        .HasColumnType("text");

                    b.Property<string>("HtmlRedirectHttpReferral")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProxyBotBlock")
                        .HasColumnType("text");

                    b.Property<string>("UniqueClickLimit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AntiFraudSettings");
                });

            modelBuilder.Entity("Interface.DTOs.AutomationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alarm")
                        .HasColumnType("text");

                    b.Property<long?>("AutomationRuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("BlockLevel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BlockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentValue")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("TargetLabel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutomationLogs");
                });

            modelBuilder.Entity("Interface.DTOs.AutomationRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Advertiser")
                        .HasColumnType("text");

                    b.Property<string>("Alarm")
                        .HasColumnType("text");

                    b.Property<bool?>("AlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("BlockLevel")
                        .HasColumnType("text");

                    b.Property<string>("Clicks")
                        .HasColumnType("text");

                    b.Property<string>("CompareType")
                        .HasColumnType("text");

                    b.Property<string>("Conversion")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataLookBack")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Field")
                        .HasColumnType("text");

                    b.Property<string>("Impressions")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaxValue")
                        .HasColumnType("text");

                    b.Property<string>("MinValue")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("OffersJson")
                        .HasColumnType("text");

                    b.Property<string>("ReportStatus")
                        .HasColumnType("text");

                    b.Property<string>("ResumeAfter")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("WhitelistOffers")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("Interface.DTOs.CappingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffiliateVisibility")
                        .HasColumnType("text");

                    b.Property<bool?>("CappingTimezoneEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CappingType")
                        .HasColumnType("text");

                    b.Property<decimal?>("CappingValue")
                        .HasColumnType("numeric");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EarlierNotificationThreshold")
                        .HasColumnType("numeric");

                    b.Property<bool?>("EnableRule")
                        .HasColumnType("boolean");

                    b.Property<string>("Events")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationEmail")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("OverCappingAction")
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.Property<string>("RuleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CappingRules");
                });

            modelBuilder.Entity("Interface.DTOs.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffiliateIds")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateMode")
                        .HasColumnType("text");

                    b.Property<string>("CouponCode")
                        .HasColumnType("text");

                    b.Property<string>("CouponType")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quota")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int?>("UsedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Interface.DTOs.Creative", b =>
                {
                    b.Property<long>("CreativeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CreativeID"));

                    b.Property<string>("AffiliateTrackingURL")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferID")
                        .HasColumnType("bigint");

                    b.Property<string>("Preview")
                        .HasColumnType("text");

                    b.Property<decimal?>("Size")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("CreativeID");

                    b.ToTable("Creative");
                });

            modelBuilder.Entity("Interface.DTOs.DefaultMailerTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DefaultMailerTemplates");
                });

            modelBuilder.Entity("Interface.DTOs.EventGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Approval")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MultiConversion")
                        .HasColumnType("text");

                    b.Property<string>("MultiConversionIp")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventGoals");
                });

            modelBuilder.Entity("Interface.DTOs.EventSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConversionApproval")
                        .HasColumnType("text");

                    b.Property<string>("ConversionWaitingTime")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPostbackEvent")
                        .HasColumnType("text");

                    b.Property<string>("EventMismatchAction")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MultiConversion")
                        .HasColumnType("text");

                    b.Property<string>("MultiConversionIp")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("EventSettings");
                });

            modelBuilder.Entity("Interface.DTOs.FallbackIntegration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnableFallback")
                        .HasColumnType("text");

                    b.Property<string>("Erid")
                        .HasColumnType("text");

                    b.Property<long?>("FallbackOfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("FallbackOfferReportsAffiliates")
                        .HasColumnType("text");

                    b.Property<string>("FallbackUrl")
                        .HasColumnType("text");

                    b.Property<string>("ForceAffiliateLandingRedirect")
                        .HasColumnType("text");

                    b.Property<string>("HtmlJsCode")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("PostbackType")
                        .HasColumnType("text");

                    b.Property<string>("UrlToReplace")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FallbackIntegrations");
                });

            modelBuilder.Entity("Interface.DTOs.LandingPage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AffiliateId")
                        .HasColumnType("bigint");

                    b.Property<string>("AffiliateMode")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Fallback")
                        .HasColumnType("boolean");

                    b.Property<string>("FallbackName")
                        .HasColumnType("text");

                    b.Property<string>("FallbackUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("FallbackWeight")
                        .HasColumnType("numeric");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("Targeting")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .HasColumnType("text");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("LandingPage");
                });

            modelBuilder.Entity("Interface.DTOs.LinkTestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("FinalStatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OsDevice")
                        .HasColumnType("text");

                    b.Property<int>("RedirectCount")
                        .HasColumnType("integer");

                    b.Property<string>("ResultText")
                        .HasColumnType("text");

                    b.Property<long?>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LinkTestResults");
                });

            modelBuilder.Entity("Interface.DTOs.LinkTesterRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdvertiserAppId")
                        .HasColumnType("text");

                    b.Property<long?>("AdvertiserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AllowedHttpStatuses")
                        .HasColumnType("text");

                    b.Property<string>("AllowedRedirection")
                        .HasColumnType("text");

                    b.Property<string>("AppIdMatch")
                        .HasColumnType("text");

                    b.Property<string>("Browser")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomUrl")
                        .HasColumnType("text");

                    b.Property<string>("Health")
                        .HasColumnType("text");

                    b.Property<string>("HealthyCheckThreshold")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MinimumOneRedirect")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResaleDetection")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("StopOffer")
                        .HasColumnType("boolean");

                    b.Property<string>("TestCountry")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LinkTesterRules");
                });

            modelBuilder.Entity("Interface.DTOs.MailerLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdvertiserCountry")
                        .HasColumnType("text");

                    b.Property<long?>("AdvertiserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AffiliateCountry")
                        .HasColumnType("text");

                    b.Property<long?>("AffiliateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Bcc")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("BulkAdvertiserStatus")
                        .HasColumnType("text");

                    b.Property<string>("BulkAffiliateStatus")
                        .HasColumnType("text");

                    b.Property<string>("Cc")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer");

                    b.Property<string>("Recipients")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<long?>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MailerLogs");
                });

            modelBuilder.Entity("Interface.DTOs.MailerTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MailerTemplates");
                });

            modelBuilder.Entity("Interface.DTOs.NetworkSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppsFlyerAccessKey")
                        .HasColumnType("text");

                    b.Property<string>("AppsFlyerClickSigningMode")
                        .HasColumnType("text");

                    b.Property<string>("ClickIpv4FilterMode")
                        .HasColumnType("text");

                    b.Property<string>("ClickIpv4FilterRanges")
                        .HasColumnType("text");

                    b.Property<long?>("ClickSigningAdvertiserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ConversionsOutOfAllowedCountries")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("CustomLoginPlatformDomain")
                        .HasColumnType("text");

                    b.Property<string>("CustomPrivacyPolicy")
                        .HasColumnType("text");

                    b.Property<string>("CustomTermsAndConditionsBody")
                        .HasColumnType("text");

                    b.Property<string>("CustomTermsAndConditionsTitle")
                        .HasColumnType("text");

                    b.Property<string>("CustomTrackingDomain")
                        .HasColumnType("text");

                    b.Property<bool>("DataMaskingDeviceId")
                        .HasColumnType("boolean");

                    b.Property<bool>("DataMaskingIpAddress")
                        .HasColumnType("boolean");

                    b.Property<long?>("DefaultAdvertiserManagerUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultAffiliateManagerUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultTrackingDomain")
                        .HasColumnType("text");

                    b.Property<string>("DefaultTrackingLinkTokens")
                        .HasColumnType("text");

                    b.Property<string>("DefaultTrackingProtocol")
                        .HasColumnType("text");

                    b.Property<string>("DefaultUniqueIdFields")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeDashboardCustomization")
                        .HasColumnType("text");

                    b.Property<string>("GlobalFallbackUrl")
                        .HasColumnType("text");

                    b.Property<string>("IpSource")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LandingPageMismatch")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("LoginAccessTypes")
                        .HasColumnType("text");

                    b.Property<string>("LoginPlatformDomain")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfferDefaultTermsAndConditions")
                        .HasColumnType("text");

                    b.Property<string>("PostbackErrorAlertEmail")
                        .HasColumnType("text");

                    b.Property<int?>("PostbackErrorThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("TermsAndConditions")
                        .HasColumnType("text");

                    b.Property<long?>("TestAffiliateId")
                        .HasColumnType("bigint");

                    b.Property<string>("TestIps")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<string>("TrackingDomain")
                        .HasColumnType("text");

                    b.Property<bool>("TrackingLinkPreviewEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("NetworkSettings");
                });

            modelBuilder.Entity("Interface.DTOs.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdvertiserCurrency")
                        .HasColumnType("text");

                    b.Property<int?>("AdvertiserId")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertiserModel")
                        .HasColumnType("text");

                    b.Property<decimal?>("AdvertiserPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("AdvertiserUrlBuilder")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateCurrency")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateModel")
                        .HasColumnType("text");

                    b.Property<decimal?>("AffiliatePrice")
                        .HasColumnType("numeric");

                    b.Property<bool?>("AlertToAffiliates")
                        .HasColumnType("boolean");

                    b.Property<string>("AppId")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("DailyEndTime")
                        .HasColumnType("interval");

                    b.Property<bool?>("DailyScheduleEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("DailyStartTime")
                        .HasColumnType("interval");

                    b.Property<bool?>("DeepLinks")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalOfferId")
                        .HasColumnType("text");

                    b.Property<bool?>("HidePayout")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LandingPage")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OfferCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("OfferDescription")
                        .HasColumnType("text");

                    b.Property<string>("OfferName")
                        .HasColumnType("text");

                    b.Property<string>("OfferPreviewUrl")
                        .HasColumnType("text");

                    b.Property<string>("OfferType")
                        .HasColumnType("text");

                    b.Property<string>("OfferUrl")
                        .HasColumnType("text");

                    b.Property<string>("OfferVisibility")
                        .HasColumnType("text");

                    b.Property<string>("PaOfferTerms")
                        .HasColumnType("text");

                    b.Property<string>("PrivateNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Styles")
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<string>("Tokens")
                        .HasColumnType("text");

                    b.Property<string>("UploadLogo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("Interface.DTOs.OfferCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferCategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("OfferCategory", (string)null);
                });

            modelBuilder.Entity("Interface.DTOs.OfferLinkingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdvertiserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AffiliateIds")
                        .HasColumnType("text");

                    b.Property<string>("AffiliatesMode")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxPayout")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPayout")
                        .HasColumnType("numeric");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferIds")
                        .HasColumnType("text");

                    b.Property<string>("OffersMode")
                        .HasColumnType("text");

                    b.Property<string>("PayoutCurrency")
                        .HasColumnType("text");

                    b.Property<string>("PayoutModel")
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OfferLinkingRules");
                });

            modelBuilder.Entity("Interface.DTOs.PayoutRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AffiliateVisibility")
                        .HasColumnType("text");

                    b.Property<string>("ConditionsJson")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<bool?>("EnableRule")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("PayoutModel")
                        .HasColumnType("text");

                    b.Property<decimal?>("PayoutValue")
                        .HasColumnType("numeric");

                    b.Property<string>("RevenueModel")
                        .HasColumnType("text");

                    b.Property<decimal?>("RevenueValue")
                        .HasColumnType("numeric");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.Property<string>("RulePriority")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PayoutRules");
                });

            modelBuilder.Entity("Interface.DTOs.ProductFeed", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdvertiserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AffiliateIds")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppendTokens")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SyncFrequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductFeeds");
                });

            modelBuilder.Entity("Interface.DTOs.RetargetingTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AffiliateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RetargetingTags");
                });

            modelBuilder.Entity("Interface.DTOs.ShortUrl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AffiliateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("Interface.DTOs.SmtpSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromEmail")
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmtpSettings");
                });

            modelBuilder.Entity("Interface.DTOs.SuppressionList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromLines")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .HasColumnType("text");

                    b.Property<string>("SubjectLines")
                        .HasColumnType("text");

                    b.Property<string>("UnsubscribeUrl")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SuppressionLists");
                });

            modelBuilder.Entity("Interface.DTOs.TargetingRules", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionOnClicks")
                        .HasColumnType("text");

                    b.Property<string>("ActionOnConversions")
                        .HasColumnType("text");

                    b.Property<string>("ActionOnImpressions")
                        .HasColumnType("text");

                    b.Property<string>("AffiliateVisibility")
                        .HasColumnType("text");

                    b.Property<string>("Browser")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ISP")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("RuleName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TargetingRules");
                });

            modelBuilder.Entity("Interface.DTOs.TopOffer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kpi")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OfferId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TopOffers");
                });

            modelBuilder.Entity("Interface.DTOs.TopOfferMailerLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AffiliateId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("BulkApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emails")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OfferIds")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("TopOfferIds")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TopOfferMailerLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
